### PR TITLE
Change trim whitespace UI option to affect trimWhitespace control fil…

### PR DESCRIPTION
**Pull request by catstavi**
* Change trim whitespace UI option to affect trimWhitespace control file flag
* set trimServerWhitespace to default to false, meaning replaces will be whitespace sensitive by default
* set setAsideErrors to default to true

### CODE REVIEW

**Comment by vilterp** [comment]
Looks good — how are we messaging this change to customers?

**Comment by catstavi** [comment]
Good question, I'll work with Nithya on that. Also planning to make a jar for CS to test before officially releasing.

**Comment by vilterp** [comment]
Yeah, making one of those question mark => popout things is a good option I think, since users will see it whether or not they receive some release notes email…

**Comment by catstavi** [comment]
Really? A info pop up for what a box labeled "Trim whitespace" does now that it actually trims whitespace?

**Comment by catstavi** [comment]
Added the info panel: 
screen shot 2016-07-28 at 1 43 21 pm

**Comment by vilterp** [comment]
:shipit:

**Pull request merged**
